name: Compilar Vignaud PRO

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:

      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Compilar aplicación
        shell: pwsh
        run: |
          pyinstaller `
            --noconfirm `
            --windowed `
            --onedir `
            --clean `
            --name VignaudPRO `
            main.py

      - name: Comprimir aplicación
        shell: pwsh
        run: |
          Compress-Archive `
            -Path dist/VignaudPRO/* `
            -DestinationPath dist/VignaudPRO.zip

      - name: Publicar ZIP
        uses: actions/upload-artifact@v4
        with:
          name: VignaudPRO
          path: dist/VignaudPRO.zip
