name: Compilar EXE

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:

      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if exist requirements.txt pip install -r requirements.txt

      - name: Crear EXE
        run: |
          pyinstaller --onefile --name Renombrador_Vignaud main.py

      - name: Subir EXE
        uses: actions/upload-artifact@v4
        with:
          name: Renombrador_Vignaud
          path: dist/Renombrador_Vignaud.exe
